global:
  scrape_interval:     60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: prometheus
  - job_name: java
    file_sd_configs:
      - files:
        - '/usr/local/prometheus/targets-jvm.json'
        refresh_interval: 5m

rule_files:
  - "/usr/local/prometheus/node_rules.yaml"
  - "/usr/local/prometheus/node_alerts.yaml"

